### ISSUE TITLE
Doesn't work for new Go versions (1.12)

### ISSUE THREAD

**Issue by omersaraf** [karlseguin/gofake#1]
On new versions Go adds dashes for functions names (using reflect) therefor Stubbing and Mocking doesn't work.

The functions are being registered without dashes, but when Stub looks for them it searches with dashes.

Adding the line 
```
	function = strings.Split(function, "-")[0]
```

in getFunctionName solves it

```
func getFunctionName(pc uintptr) string {
	name := runtime.FuncForPC(pc).Name()
	dot := strings.LastIndex(name, ".")
	function := name[dot+1:]
	function = strings.Split(function, "-")[0]
	if index := strings.LastIndex(function, "·"); index != -1 {
		return function[:index]
	}
	return function
}
```

**Comment by karlseguin** [comment]
Not the prettiest fix, but I couldn't find another way to do it, thanks!
